// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Account
{
    public int AccId { get; set; }

    public int? RoleId { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public string Phone { get; set; }

    public string Mail { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Img { get; set; }

    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    public virtual ICollection<Customer> Customers { get; set; } = new List<Customer>();

    public virtual ICollection<Doctor> Doctors { get; set; } = new List<Doctor>();

    public virtual Role Role { get; set; }
}