// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class BioSampleStatus
{
    public int StatusId { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<BioSample> BioSamples { get; set; } = new List<BioSample>();
}