// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class BioSample
{
    public int BsId { get; set; }

    public int? TpId { get; set; }

    public int? BtId { get; set; }

    public string BsName { get; set; }

    public int? Status { get; set; }

    public DateOnly? CollectionDate { get; set; }

    public string StorageLocation { get; set; }

    public int? BqsId { get; set; }

    public string Note { get; set; }

    public virtual BioQualityStatus Bqs { get; set; }

    public virtual BioType Bt { get; set; }

    public virtual BioSampleStatus StatusNavigation { get; set; }

    public virtual TreatmentPlan Tp { get; set; }
}