// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int? AccId { get; set; }

    public int? DocId { get; set; }

    public int? DsId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreateAt { get; set; }

    public string Note { get; set; }

    public virtual Account Acc { get; set; }

    public virtual Doctor Doc { get; set; }

    public virtual DoctorSchedule Ds { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}