// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Certificate
{
    public int CerId { get; set; }

    public string CerName { get; set; }

    public int? DocId { get; set; }

    public string FilePath { get; set; }

    public virtual Doctor Doc { get; set; }
}