// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class DocCertificate
{
    public int DocId { get; set; }

    public int CerId { get; set; }

    public string FilePath { get; set; }

    public virtual Certificate Cer { get; set; }

    public virtual Doctor Doc { get; set; }
}