// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class PaymentType
{
    public int PaymentTypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();
}