// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int? PaymentTypeId { get; set; }

    public int? BookingId { get; set; }

    public int? TreatmentPlansId { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int? MethodId { get; set; }

    public int? StatusId { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual MethodPayment Method { get; set; }

    public virtual PaymentType PaymentType { get; set; }

    public virtual PaymentStatus Status { get; set; }

    public virtual TreatmentPlan TreatmentPlans { get; set; }
}