// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Remind
{
    public int RemindId { get; set; }

    public int? SdId { get; set; }

    public string Message { get; set; }

    public DateOnly? ReminderDay { get; set; }

    public bool? IsTaken { get; set; }

    public virtual StepDetail Sd { get; set; }
}