// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class SlotSchedule
{
    public int SlotId { get; set; }

    public TimeOnly? SlotStart { get; set; }

    public TimeOnly? SlotEnd { get; set; }

    public virtual ICollection<DoctorSchedule> DoctorSchedules { get; set; } = new List<DoctorSchedule>();
}