// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class StepDetail
{
    public int SdId { get; set; }

    public int? TpId { get; set; }

    public int? TsId { get; set; }

    public int? DocId { get; set; }

    public string StepName { get; set; }

    public string Note { get; set; }

    public int? Status { get; set; }

    public int? DsId { get; set; }

    public string DrugName { get; set; }

    public string Dosage { get; set; }

    public virtual ICollection<BioSample> BioSamples { get; set; } = new List<BioSample>();

    public virtual Doctor Doc { get; set; }

    public virtual DoctorSchedule Ds { get; set; }

    public virtual ICollection<Remind> Reminds { get; set; } = new List<Remind>();

    public virtual StepDetailStatus StatusNavigation { get; set; }

    public virtual ICollection<Test> Tests { get; set; } = new List<Test>();

    public virtual TreatmentPlan Tp { get; set; }

    public virtual TreatmentStep Ts { get; set; }
}