// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class Test
{
    public int TestId { get; set; }

    public int? TpId { get; set; }

    public int? TestTypeId { get; set; }

    public int? SdId { get; set; }

    public DateOnly? TestDate { get; set; }

    public int? TqsId { get; set; }

    public DateOnly? ResultDay { get; set; }

    public string Note { get; set; }

    public string FilePath { get; set; }

    public int? Status { get; set; }

    public virtual StepDetail Sd { get; set; }

    public virtual TestStatus StatusNavigation { get; set; }

    public virtual TestType TestType { get; set; }

    public virtual TreatmentPlan Tp { get; set; }

    public virtual TestQualityStatus Tqs { get; set; }
}