// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class TestType
{
    public int TestTypeId { get; set; }

    public string Person { get; set; }

    public string TestName { get; set; }

    public virtual ICollection<Test> Tests { get; set; } = new List<Test>();
}