// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class TestQualityStatus
{
    public int TqsId { get; set; }

    public string TqsName { get; set; }

    public virtual ICollection<Test> Tests { get; set; } = new List<Test>();
}