// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class TreatmentPlan
{
    public int TpId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Result { get; set; }

    public int? SerId { get; set; }

    public int? CusId { get; set; }

    public int? DocId { get; set; }

    public int? Status { get; set; }

    public virtual ICollection<BioSample> BioSamples { get; set; } = new List<BioSample>();

    public virtual Customer Cus { get; set; }

    public virtual Doctor Doc { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Service Ser { get; set; }

    public virtual TreatmentPlanStatus StatusNavigation { get; set; }

    public virtual ICollection<StepDetail> StepDetails { get; set; } = new List<StepDetail>();

    public virtual ICollection<Test> Tests { get; set; } = new List<Test>();
}