// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SWP.Models;

public partial class TreatmentStep
{
    public int TsId { get; set; }

    public string StepName { get; set; }

    public string Description { get; set; }

    public int? SerId { get; set; }

    public virtual Service Ser { get; set; }

    public virtual ICollection<StepDetail> StepDetails { get; set; } = new List<StepDetail>();
}